[project]
name = "rag-pract"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Ammar", email = "ammarahmer59@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
rag-pract = "rag_pract:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
