[project]
name = "rag-pract"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Ammar", email = "ammarahmer59@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.4.0",
    "langchain>=1.4.3",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.6",
    "msoffcrypto-tool>=6.0.0",
    "networkx>=3.7",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "pymupdf>=1.28.2",
    "pypdf>=6.19.0",
    "unstructured>=0.27.10",
]

[project.scripts]
rag-pract = "rag_pract:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
